Adjustments after type-check

diff --git a/scripts/deploy b/scripts/deploy
--- a/scripts/deploy
+++ b/scripts/deploy
@@ -36,12 +36,13 @@ cp env.testing $WD/api/tests/Support/bootstrap/.env.testing
 cp env.register $WD/apps/reg/.env
 
 cd $WD
-APIVERSION=`php -r '$version=json_decode(file_get_contents("builds.json")); echo $version->api->major . "." . $version->api->minor . "." . $version->api->micro . "." . $version->api->build;'`
-REGVERSION=`php -r '$version=json_decode(file_get_contents("builds.json")); echo $version->register->major . "." . $version->register->minor . "." . $version->register->micro . "." . $version->register->build;'`
+BUILDNR=`php -r '$version=json_decode(file_get_contents("build.json")); echo $version->build;'`
+APIVERSION=`php -r '$version=json_decode(file_get_contents("versions.json")); echo $version->api->major . "." . $version->api->minor . "." . $version->api->micro;'`
+REGVERSION=`php -r '$version=json_decode(file_get_contents("versions.json")); echo $version->register->major . "." . $version->register->minor . "." . $version->register->micro;'`
 
 echo "Patching versions in env files" >> $LOG
-cat $WD/api/.env | sed "s/APP_VERSION=.*/APP_VERSION=$APIVERSION/" > tmp; mv tmp $WD/api/.env
-cat $WD/apps/reg/.env | sed "s/VITE_VERSION=.*/VITE_VERSION=$REGVERSION/" > tmp; mv tmp $WD/apps/reg/.env
+cat $WD/api/.env | sed "s/APP_VERSION=.*/APP_VERSION=$APIVERSION\.$BUILDNR/" > tmp; mv tmp $WD/api/.env
+cat $WD/apps/reg/.env | sed "s/VITE_VERSION=.*/VITE_VERSION=$REGVERSION\.$BUILDNR/" > tmp; mv tmp $WD/apps/reg/.env
 
 cd api
 
@@ -139,7 +140,7 @@ echo "Installing NPM modules" >> $LOG
 npm install --production=false >> $LOG 2>&1
 chmod u+x node_modules/.bin/* >> $LOG
 
-echo "Running tests for Registration Application" >> $LOG
+echo "Running type-check tests for Registration Application" >> $LOG
 npm run type-check >> $LOG 2>&1
 EC="$?"
 
@@ -149,6 +150,18 @@ then
     echo "Exit code on type-check $EC" >> $LOG
     exit 1
 fi
+
+echo "Running unit tests for Registration Application" >> $LOG
+npm run test:unit -- --run >> $LOG 2>&1
+EC="$?"
+
+if [[ ! "x$EC" = "x0" ]]
+then
+    echo "Error running unit tests"
+    echo "Exit code on unit tests $EC" >> $LOG
+    exit 1
+fi
+
 
 echo "Creating application files"
 NODE_ENV=development npm run build-only -- --mode development --minify false >> $LOG 2>&1
